apiVersion: apps/v1
kind: Deployment
metadata:
  name: bin-calc-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-calc
  template:
    metadata:
      labels:
        app: binary-calc
    spec:
      containers:
        - image: binaryCalculator_ImageName
          name: binary-calc
          ports:
            - containerPort: 8080
              name: binary-calc