apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-calc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binary-calculator
  template:
    metadata:
      labels:
        app: binary-calculator
    spec:
      containers:
        - image: binaryCalculator_ImageName
          name: binary-calculator
          ports:
            - containerPort: 8080
              name: binary-calculator